### ISSUE TITLE
Short docs about how to use the plug-in

### ISSUE THREAD

**Issue by aadrian** [yaroot/gitbucket-pages-plugin#5]
Would be nice to have some short docs about how to use the plug-in's functionality (not just how to install it)

Thank you.

**Comment by yaroot** [comment]
also welcome to fix my english

**Comment by aadrian** [comment]
Thank you!

Few notes:
- The branch should be called ```gb-pages``` not ```gh-pages``` :)  (or maybe even ```gitbucket-pages``` to avoid confusion).
- How to handle images and stylesheets (or other resources besides HTML)?
- Would be nice if the official demo https://gitbucket.herokuapp.com/ would have this plug-in installed with a demo page, in order to be linked from here.

**Comment by yaroot** [comment]
- it's nice to have it named `gh-pages` if you have the repository opensourced but kept it on gitbucket. could support fallbacks (try `gb-pages`, if not found then `gh-pages`), ideas?
- updated readme
- it's better to discuss in the gitter room (all gitbucket devs are there) :-)

**Comment by aadrian** [comment]
> it's nice to have it named gh-pages if you have the repository opensourced but kept it on gitbucket. could support fallbacks (try gb-pages, if not found then gh-pages), ideas?

Of course ```gh-pages``` has more advantages, but it's kind of proprietary, hence my proposal to rename it. When moving a repository from GH to GB or backwards, the users could simply rename the orphan branch (we just need to documented it).

**Comment by yaroot** [comment]
What about supporting multiple branch names, try load from gb-pages first, if the branch isn't exist then try gh-pages.

**Comment by aadrian** [comment]
> What about supporting multiple branch names, try load from gb-pages first, if the branch isn't exist then try gh-pages.

That might be a solution too ("GH compatibility" feature :) ). However if a user migrates a repo from GB to GH, it still needs to know and rename the orphan branch to ```gh-pages```
