### ISSUE TITLE
Release for GitBucket 4.6

### ISSUE THREAD

**Issue by zexxar** [yaroot/gitbucket-pages-plugin#8]
Can you please add a version for GitBucket 4.6?

Thank you.

**Comment by t-tsutsumi** [comment]
Please try the following:
```sql
UPDATE VERSIONS SET VERSION = '0.7' WHERE MODULE_ID = 'pages';
```

@yaroot:
The `versions` field on `Plugin.scala` needs to be clearly defined.

**Comment by yaroot** [comment]
@t-tsutsumi it is, does reading from jar manifest cause problem?

@zexxar 0.7 works fine on my installation, is there any errors?

**Comment by zexxar** [comment]
@yaroot The problem for me is that unlike the other plugins I use (e.g. network, gist) it doesn't appear in the list of installed plugins, although all the plugin jars are in the same folder. That's why it shouldn't be a configuration problem on my side and so I thought that it maybe due to some imcompatibility with the latest Gitbucket version.

**Comment by yaroot** [comment]
@zexxar are you using container or just `java -jar`

**Comment by yaroot** [comment]
figured out the migration, waiting for new version to compile
